version: '3.8'

services:

  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.0-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env
  web:
    container_name: yamdb
    build:
      context: ../
      dockerfile: api_yamdb/Dockerfile
    # image: sasha0090/yamdb
    command: bash -c "python manage.py makemigrations reviews users && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn api_yamdb.wsgi:application -b 0.0.0.0:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - "8000"
  nginx:
    # образ, из которого должен быть запущен контейнер
    image: nginx:1.21.3-alpine

    # запросы с внешнего порта 80 перенаправляем на внутренний порт 80
    ports:
      - "80:80"

    volumes:
      # При сборке скопировать созданный конфиг nginx из исходной директории 
      # в контейнер и сохранить его в директорию /etc/nginx/conf.d/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      # Контейнер nginx будет работать с данными, хранящиеся в томе static_value, 
      # через свою директорию /var/html/static/
      - static_value:/var/html/static/

      # Данные, хранящиеся в томе media_value, будут доступны в контейнере nginx
      # через директорию /var/html/media/
      - media_value:/var/html/media/

    depends_on:
      # Контейнер nginx должен быть запущен после контейнера web
      - web

volumes:
  # Новые тома 
  static_value:
  media_value:
